DROP POLICY IF EXISTS tenant_isolation ON campaign_recipients;
DROP POLICY IF EXISTS tenant_isolation ON campaigns;
DROP POLICY IF EXISTS tenant_isolation ON audiences;
DROP POLICY IF EXISTS tenant_isolation ON contact_tags;
DROP POLICY IF EXISTS tenant_isolation ON tags;
DROP POLICY IF EXISTS tenant_isolation ON contacts;

ALTER TABLE campaign_recipients NO FORCE ROW LEVEL SECURITY;
ALTER TABLE campaigns NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audiences NO FORCE ROW LEVEL SECURITY;
ALTER TABLE contact_tags NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tags NO FORCE ROW LEVEL SECURITY;
ALTER TABLE contacts NO FORCE ROW LEVEL SECURITY;

ALTER TABLE campaign_recipients DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE audiences DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM app_user;
DROP ROLE IF EXISTS app_user;
